"""Script interpreter for ezweb monolithic mode.

Supports nested DSL operations for dynamic content generation:

  File operations:
    ``read_file``    – read a file from disk, optionally save to a variable
    ``write_file``   – write content to a file
    ``delete_file``  – delete a file
    ``file_exists``  – check whether a file exists

  Variable & data:
    ``variable``       – reference a previously stored variable
    ``json_analyze``   – parse JSON and extract a value by key
    ``json_stringify`` – convert a value to a JSON string

  String operations:
    ``concat``   – concatenate multiple values
    ``replace``  – replace substring occurrences
    ``split``    – split a string into a list
    ``join``     – join a list with a separator
    ``trim``     – strip leading/trailing whitespace
    ``upper``    – convert to uppercase
    ``lower``    – convert to lowercase

  Sequence operations:
    ``slice``  – slice a string or list
    ``length`` – get length of a string or list
    ``at``     – retrieve an element by index

  Math operations:
    ``add``  – addition
    ``sub``  – subtraction
    ``mul``  – multiplication
    ``div``  – division
    ``mod``  – modulo

  Control flow & utilities:
    ``return``    – terminate execution and return a value
    ``format``    – format a template string with variables
    ``timestamp`` – get current Unix timestamp / formatted datetime
    ``if``        – conditional value selection
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class JsExpr:
    """Represents a JavaScript expression generated by the script interpreter.

    When the interpreter is in *event mode* (``is_event=True``), ``self.*``
    variable references produce ``JsExpr`` objects instead of resolved Python
    values.  Downstream commands (``format``, ``alert``) recognise these and
    emit JavaScript runtime expressions rather than quoted strings.
    """

    def __init__(self, expr: str) -> None:
        self.expr = expr

    def __str__(self) -> str:
        return self.expr

    def __repr__(self) -> str:
        return f"JsExpr({self.expr!r})"


class ScriptError(Exception):
    """Raised when a script operation fails."""

    def __init__(self, message: str, detail: dict[str, str] | None = None) -> None:
        super().__init__(message)
        self.detail = detail


def _is_command_dict(value: dict[str, Any], command_keys: frozenset[str]) -> bool:
    return bool(command_keys & value.keys())


class ScriptInterpreter:
    """Executes ezweb DSL scripts for dynamic content generation."""

    _COMMAND_KEYS = frozenset(
        {
            "read_file",
            "write_file",
            "delete_file",
            "file_exists",
            "variable",
            "json_analyze",
            "json_stringify",
            "return",
            "concat",
            "replace",
            "split",
            "join",
            "trim",
            "upper",
            "lower",
            "slice",
            "length",
            "at",
            "add",
            "sub",
            "mul",
            "div",
            "mod",
            "format",
            "timestamp",
            "if",
            "alert",
            "fetch",
            "store",
        }
    )

    def __init__(
        self,
        base_path: str | Path | None = None,
        initial_variables: dict[str, Any] | None = None,
        is_event: bool = False,
    ) -> None:
        self._variables: dict[str, Any] = {}
        if initial_variables:
            self._variables.update(initial_variables)
        self._base_path = Path(base_path) if base_path else Path.cwd()
        self._path: list[str] = []
        self._is_event = is_event

    @property
    def path(self) -> list[str]:
        return list(self._path)

    # Public API

    def execute(self, script_data: dict[str, Any]) -> Any:
        """Execute a script and return the result."""
        if not isinstance(script_data, dict):
            raise ScriptError(
                f"Script must be a dict, got {type(script_data).__name__}"
            )

        result = None
        for key in list(script_data.keys()):
            if key == "return":
                self._path.append("return")
                ok = False
                try:
                    action = script_data[key]
                    if not isinstance(action, dict):
                        raise ScriptError("'return' action must be a dict")
                    result = self._eval(action.get("data"))
                    ok = True
                    return result
                finally:
                    if ok:
                        self._path.pop()

            result = self._dispatch(key, script_data[key])

        return result

    # Recursive evaluator

    def _eval(self, expr: Any) -> Any:
        """Evaluate any expression recursively, resolving nested commands."""
        if not isinstance(expr, dict):
            return expr

        if not _is_command_dict(expr, self._COMMAND_KEYS):
            return expr

        for cmd in self._COMMAND_KEYS & expr.keys():
            return self._dispatch(cmd, expr[cmd])

        return expr

    # Dispatch table

    def _dispatch(self, cmd: str, action: Any) -> Any:
        """Route a command name to its implementation."""
        _dispatch_map = {
            "variable": self._do_variable,
            "read_file": self._do_read_file,
            "write_file": self._do_write_file,
            "delete_file": self._do_delete_file,
            "file_exists": self._do_file_exists,
            "json_analyze": self._do_json_analyze,
            "json_stringify": self._do_json_stringify,
            "concat": self._do_concat,
            "replace": self._do_replace,
            "split": self._do_split,
            "join": self._do_join,
            "trim": self._do_trim,
            "upper": self._do_upper,
            "lower": self._do_lower,
            "slice": self._do_slice,
            "length": self._do_length,
            "at": self._do_at,
            "add": self._do_add,
            "sub": self._do_sub,
            "mul": self._do_mul,
            "div": self._do_div,
            "mod": self._do_mod,
            "format": self._do_format,
            "timestamp": self._do_timestamp,
            "if": self._do_if,
            "alert": self._do_alert,
            "fetch": self._do_fetch,
            "store": self._do_store,
        }

        if cmd == "variable":
            action = {"variable": action}

        handler = _dispatch_map.get(cmd)
        if handler is None:
            raise ScriptError(f"Unknown command {cmd!r}")

        self._path.append(cmd)
        ok = False
        try:
            result = handler(action)
            ok = True
            return result
        finally:
            if ok:
                self._path.pop()

    # Helper: optional save

    def _maybe_save(self, action: dict[str, Any], value: Any) -> None:
        save = action.get("save")
        if save is not None:
            if not isinstance(save, dict) or "variable" not in save:
                raise ScriptError("'save' must be a dict like {'variable': 'name'}")
            var_name = save["variable"]
            if not isinstance(var_name, str):
                raise ScriptError(
                    f"Variable name must be a string, got {type(var_name).__name__}"
                )
            if var_name.startswith("$"):
                raise ScriptError(
                    f"Cannot save to reserved variable '{var_name}'. "
                    f"Names starting with '$' are system-reserved."
                )
            self._variables[var_name] = value

    @staticmethod
    def _require_str(value: Any, label: str) -> str:
        if not isinstance(value, str):
            raise ScriptError(f"{label} must be a string, got {type(value).__name__}")
        return value

    @staticmethod
    def _require_num(value: Any, label: str) -> int | float:
        if not isinstance(value, (int, float)):
            raise ScriptError(f"{label} must be a number, got {type(value).__name__}")
        return value

    # File operations

    def _resolve_path(self, file_ref: Any) -> Path:
        path_str = self._require_str(self._eval(file_ref), "'file'")
        return self._base_path / path_str

    def _do_read_file(self, action: dict[str, Any]) -> str:
        full_path = self._resolve_path(action.get("file"))
        try:
            content = full_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            raise ScriptError(
                f"File not found: {full_path}", detail={"file": str(action.get("file"))}
            )
        except OSError as e:
            raise ScriptError(
                f"Failed to read '{full_path}': {e}",
                detail={"file": str(action.get("file"))},
            )
        self._maybe_save(action, content)
        return content

    def _do_write_file(self, action: dict[str, Any]) -> dict[str, Any]:
        full_path = self._resolve_path(action.get("file"))
        content = self._eval(action.get("content"))
        if content is None:
            raise ScriptError("'write_file' requires a 'content' key")
        try:
            full_path.write_text(str(content), encoding="utf-8")
        except OSError as e:
            raise ScriptError(
                f"Failed to write '{full_path}': {e}",
                detail={"file": str(action.get("file"))},
            )
        result = {"file": str(full_path), "written": True}
        self._maybe_save(action, result)
        return result

    def _do_delete_file(self, action: dict[str, Any]) -> dict[str, Any]:
        full_path = self._resolve_path(action.get("file"))
        try:
            full_path.unlink()
            result = {"file": str(full_path), "deleted": True}
        except FileNotFoundError:
            result = {"file": str(full_path), "deleted": False, "reason": "not_found"}
        except OSError as e:
            raise ScriptError(f"Failed to delete '{full_path}': {e}")
        self._maybe_save(action, result)
        return result

    def _do_file_exists(self, action: dict[str, Any]) -> bool:
        full_path = self._resolve_path(action.get("file"))
        result = full_path.exists()
        self._maybe_save(action, result)
        return result

    # Variable

    def _do_variable(self, action: dict[str, Any]) -> Any:
        var_name = action.get("variable")
        if var_name is None:
            raise ScriptError(
                "'variable' requires a 'variable' key with the variable name"
            )
        var_name = self._require_str(var_name, "Variable name")

        if self._is_event and var_name.startswith("self."):
            suffix = var_name.split(".", 1)[1]
            if suffix in self._variables.get("self", {}):
                return JsExpr(f"this.{suffix}")
            return JsExpr(
                f"document.querySelector('[name={json.dumps(suffix)}]').value"
            )

        if var_name in self._variables:
            return self._variables[var_name]

        parts = var_name.split(".", 1)
        if len(parts) > 1 and parts[0] in self._variables:
            parent = self._variables[parts[0]]
            if isinstance(parent, dict) and parts[1] in parent:
                return parent[parts[1]]

        if var_name.startswith("$"):
            raise ScriptError(
                f"System variable '{var_name}' is not available in this context",
                detail={"variable": var_name},
            )

        raise ScriptError(
            f"Variable '{var_name}' is not defined", detail={"variable": var_name}
        )

    # JSON operations

    def _do_json_analyze(self, action: dict[str, Any]) -> Any:
        data = action.get("data")
        if data is None:
            raise ScriptError("'json_analyze' requires a 'data' key")
        key = action.get("key")
        if key is None:
            raise ScriptError("'json_analyze' requires a 'key' key")
        key = self._require_str(key, "'key'")

        raw = self._eval(data)
        if isinstance(raw, str):
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError as e:
                raise ScriptError(f"Failed to parse JSON: {e}", detail={"key": key})
        elif isinstance(raw, dict):
            parsed = raw
        else:
            raise ScriptError(
                f"'json_analyze' data must resolve to a JSON string or dict, "
                f"got {type(raw).__name__}"
            )

        if key not in parsed:
            raise ScriptError(
                f"Key '{key}' not found in JSON data", detail={"key": key}
            )
        result = parsed[key]
        self._maybe_save(action, result)
        return result

    def _do_json_stringify(self, action: dict[str, Any]) -> str:
        data = action.get("data")
        if data is None:
            raise ScriptError("'json_stringify' requires a 'data' key")
        indent = action.get("indent")
        result = json.dumps(self._eval(data), indent=indent, ensure_ascii=False)
        self._maybe_save(action, result)
        return result

    # String operations

    def _do_concat(self, action: dict[str, Any]) -> str:
        values = action.get("values")
        if not isinstance(values, list):
            raise ScriptError("'concat' requires a 'values' key with a list")
        result = "".join(str(self._eval(v)) for v in values)
        self._maybe_save(action, result)
        return result

    def _do_replace(self, action: dict[str, Any]) -> str:
        text = self._require_str(self._eval(action.get("text")), "'text'")
        old = self._require_str(self._eval(action.get("old")), "'old'")
        new = str(self._eval(action.get("new", "")))
        count = action.get("count", -1)
        result = text.replace(old, new, count if isinstance(count, int) else -1)
        self._maybe_save(action, result)
        return result

    def _do_split(self, action: dict[str, Any]) -> list[str]:
        text = self._require_str(self._eval(action.get("text")), "'text'")
        sep = self._eval(action.get("separator", ","))
        sep = str(sep) if sep is not None else None
        maxsplit = action.get("maxsplit", -1)
        result = text.split(sep, maxsplit if isinstance(maxsplit, int) else -1)
        self._maybe_save(action, result)
        return result

    def _do_join(self, action: dict[str, Any]) -> str:
        sep = str(self._eval(action.get("separator", "")))
        values = self._eval(action.get("values"))
        if not isinstance(values, list):
            raise ScriptError("'join' requires a 'values' key with a list")
        result = sep.join(str(v) for v in values)
        self._maybe_save(action, result)
        return result

    def _do_trim(self, action: dict[str, Any]) -> str:
        text = self._require_str(self._eval(action.get("text")), "'text'")
        result = text.strip()
        self._maybe_save(action, result)
        return result

    def _do_upper(self, action: dict[str, Any]) -> str:
        text = self._require_str(self._eval(action.get("text")), "'text'")
        result = text.upper()
        self._maybe_save(action, result)
        return result

    def _do_lower(self, action: dict[str, Any]) -> str:
        text = self._require_str(self._eval(action.get("text")), "'text'")
        result = text.lower()
        self._maybe_save(action, result)
        return result

    # Sequence operations

    def _do_slice(self, action: dict[str, Any]) -> Any:
        seq = self._eval(action.get("data"))
        start = action.get("start", 0)
        end = action.get("end")
        step = action.get("step", 1)
        if isinstance(seq, str):
            result = seq[start:end:step]
        elif isinstance(seq, list):
            result = seq[start:end:step]
        else:
            raise ScriptError(
                f"'slice' requires a string or list, got {type(seq).__name__}"
            )
        self._maybe_save(action, result)
        return result

    def _do_length(self, action: dict[str, Any]) -> int:
        data = self._eval(action.get("data"))
        if not isinstance(data, (str, list, dict)):
            raise ScriptError(
                f"'length' requires a string, list, or dict, got {type(data).__name__}"
            )
        result = len(data)
        self._maybe_save(action, result)
        return result

    def _do_at(self, action: dict[str, Any]) -> Any:
        data = self._eval(action.get("data"))
        index = action.get("index")
        if index is None:
            raise ScriptError("'at' requires an 'index' key")
        if not isinstance(index, int):
            raise ScriptError(f"'index' must be an integer, got {type(index).__name__}")
        if not isinstance(data, (str, list)):
            raise ScriptError(
                f"'at' requires a string or list, got {type(data).__name__}"
            )
        try:
            result = data[index]
        except IndexError:
            raise ScriptError(
                f"Index {index} out of range for data of length {len(data)}"
            )
        self._maybe_save(action, result)
        return result

    # Math operations

    def _math_binop(self, action: dict[str, Any], op_label: str, op) -> int | float:
        a = self._require_num(self._eval(action.get("a")), f"'{op_label}' 'a'")
        b = self._require_num(self._eval(action.get("b")), f"'{op_label}' 'b'")
        try:
            result = op(a, b)
        except ZeroDivisionError:
            raise ScriptError(f"Division by zero in '{op_label}'")
        self._maybe_save(action, result)
        return result

    def _do_add(self, action: dict[str, Any]) -> int | float:
        return self._math_binop(action, "add", lambda a, b: a + b)

    def _do_sub(self, action: dict[str, Any]) -> int | float:
        return self._math_binop(action, "sub", lambda a, b: a - b)

    def _do_mul(self, action: dict[str, Any]) -> int | float:
        return self._math_binop(action, "mul", lambda a, b: a * b)

    def _do_div(self, action: dict[str, Any]) -> int | float:
        return self._math_binop(action, "div", lambda a, b: a / b)

    def _do_mod(self, action: dict[str, Any]) -> int | float:
        return self._math_binop(action, "mod", lambda a, b: a % b)

    # Utility operations

    def _do_format(self, action: dict[str, Any]) -> str:
        template = self._require_str(self._eval(action.get("template")), "'template'")
        data = action.get("data", {})
        if isinstance(data, dict) and _is_command_dict(data, self._COMMAND_KEYS):
            data = self._eval(data)
        if isinstance(data, dict):
            data = {k: self._eval(v) for k, v in data.items()}
        if not isinstance(data, dict):
            raise ScriptError(
                f"'format' 'data' must resolve to a dict, got {type(data).__name__}"
            )

        has_js = any(isinstance(v, JsExpr) for v in data.values())
        if has_js:
            import re

            parts = re.split(r"\{(\w+)\}", template)
            js_parts = []
            for part in parts:
                if not part:
                    continue
                if part in data and isinstance(data[part], JsExpr):
                    js_parts.append(data[part].expr)
                elif part in data:
                    escaped = str(data[part]).replace("\\", "\\\\").replace("'", "\\'")
                    if escaped:
                        js_parts.append(f"'{escaped}'")
                else:
                    escaped = part.replace("\\", "\\\\").replace("'", "\\'")
                    if escaped:
                        js_parts.append(f"'{escaped}'")
            result = (
                JsExpr(" + ".join(js_parts))
                if len(js_parts) > 1
                else (js_parts[0] if js_parts else JsExpr("''"))
            )
        else:
            try:
                result = template.format_map(data)
            except KeyError as e:
                raise ScriptError(f"Missing format key: {e}")
        self._maybe_save(action, result)
        return result

    def _do_timestamp(self, action: dict[str, Any]) -> int | str:
        fmt = action.get("format")
        if fmt is not None:
            fmt = self._require_str(self._eval(fmt), "'format'")
            tz_offset = action.get("utc_offset")
            tz = timezone.utc
            if tz_offset is not None:
                from datetime import timedelta

                tz = timezone(timedelta(hours=float(tz_offset)))
            result = datetime.now(tz=tz).strftime(fmt)
        else:
            result = int(time.time())
        self._maybe_save(action, result)
        return result

    def _do_if(self, action: dict[str, Any]) -> Any:
        cond = self._eval(action.get("condition"))
        then_branch = action.get("then")
        else_branch = action.get("else")
        result = self._eval(then_branch) if cond else self._eval(else_branch)
        self._maybe_save(action, result)
        return result

    def _do_alert(self, action: dict[str, Any]) -> str:
        data = self._eval(action.get("data"))
        if isinstance(data, JsExpr):
            result = f"alert({data.expr})"
        else:
            escaped = str(data).replace("\\", "\\\\").replace("'", "\\'")
            result = f"alert('{escaped}')"
        self._maybe_save(action, result)
        return result

    def _do_fetch(self, action: dict[str, Any]) -> str:
        url = self._require_str(self._eval(action.get("url")), "'url'")
        method = self._eval(action.get("method", "POST"))
        method = str(method) if method else "POST"
        raw_data = action.get("data", {})

        if isinstance(raw_data, dict) and _is_command_dict(
            raw_data, self._COMMAND_KEYS
        ):
            raw_data = self._eval(raw_data)
        if not isinstance(raw_data, dict):
            raise ScriptError("'fetch' 'data' must resolve to a dict")

        js_pairs = []
        for k, v in raw_data.items():
            if self._is_event and isinstance(v, str) and v.startswith("self."):
                v_resolved = self._eval({"variable": v})
            else:
                v_resolved = self._eval(v)
            js_pairs.append(f"{json.dumps(k)}:{_py_to_js_literal(v_resolved)}")
        js_obj = "{" + ",".join(js_pairs) + "}"

        result = (
            f"fetch({json.dumps(url)},{{"
            f"method:{json.dumps(method)},"
            f"headers:{{'Content-Type':'application/json'}},"
            f"body:JSON.stringify({js_obj})"
            f"}})"
            f".then(r=>r.json())"
            f".then(d=>alert(JSON.stringify(d)))"
        )
        self._maybe_save(action, result)
        return result

    def _do_store(self, action: dict[str, Any]) -> dict[str, Any]:
        file = self._require_str(self._eval(action.get("file")), "'file'")
        data = self._eval(action.get("data"))
        full_path = self._base_path / file
        try:
            full_path.write_text(
                json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
            )
        except OSError as e:
            raise ScriptError(f"Failed to store '{full_path}': {e}")
        result = {"file": str(full_path), "stored": True}
        self._maybe_save(action, result)
        return result


def _py_to_js_literal(value: Any) -> str:
    if isinstance(value, JsExpr):
        return value.expr
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, dict):
        parts = [f"{json.dumps(k)}:{_py_to_js_literal(v)}" for k, v in value.items()]
        return "{" + ",".join(parts) + "}"
    if isinstance(value, list):
        parts = [_py_to_js_literal(v) for v in value]
        return "[" + ",".join(parts) + "]"
    return json.dumps(str(value))
